#!/bin/bash
# compile_shaders.sh — Compile GLSL uber-shaders to SPIR-V and generate C header
set -e
cd "$(dirname "$0")"

SRCDIR="src/platform"
OUTDIR="src/platform"
TMPDIR="/tmp/swordigo_shaders"
mkdir -p "$TMPDIR"

echo "[Shaders] Extracting GLSL from vulkan_shaders.glsl.h..."

# Extract vertex shader GLSL (between R"glsl( and )glsl" markers)
sed -n '/VK_VERT_SHADER_GLSL/,/)glsl"/p' "$SRCDIR/vulkan_shaders.glsl.h" | \
    sed '1d;$d' > "$TMPDIR/uber.vert"

# Extract fragment shader GLSL
sed -n '/VK_FRAG_SHADER_GLSL/,/)glsl"/p' "$SRCDIR/vulkan_shaders.glsl.h" | \
    sed '1d;$d' > "$TMPDIR/uber.frag"

echo "[Shaders] Compiling vertex shader..."
glslangValidator -V "$TMPDIR/uber.vert" -o "$TMPDIR/uber.vert.spv"

echo "[Shaders] Compiling fragment shader..."
glslangValidator -V "$TMPDIR/uber.frag" -o "$TMPDIR/uber.frag.spv"

echo "[Shaders] Generating C header..."

cat > "$OUTDIR/vulkan_shaders_spirv.h" << 'HEADER_START'
// vulkan_shaders_spirv.h — Pre-compiled SPIR-V bytecode for Vulkan uber-shaders
// AUTO-GENERATED by compile_shaders.sh — DO NOT EDIT
#pragma once
#include <cstdint>

HEADER_START

# Convert vertex SPIR-V to C array
echo "static const uint32_t VK_VERT_SHADER_SPIRV[] = {" >> "$OUTDIR/vulkan_shaders_spirv.h"
xxd -i < "$TMPDIR/uber.vert.spv" | sed 's/unsigned char.*\[\] = {//;s/};$//' | \
    python3 -c "
import sys
data = bytes([int(x.strip().rstrip(','), 16) for x in sys.stdin.read().replace('\n',' ').split(',') if x.strip()])
words = []
for i in range(0, len(data), 4):
    w = int.from_bytes(data[i:i+4], 'little')
    words.append(f'0x{w:08x}')
for i in range(0, len(words), 8):
    print('    ' + ', '.join(words[i:i+8]) + ',')
" >> "$OUTDIR/vulkan_shaders_spirv.h"
echo "};" >> "$OUTDIR/vulkan_shaders_spirv.h"
echo "" >> "$OUTDIR/vulkan_shaders_spirv.h"

# Convert fragment SPIR-V to C array
echo "static const uint32_t VK_FRAG_SHADER_SPIRV[] = {" >> "$OUTDIR/vulkan_shaders_spirv.h"
xxd -i < "$TMPDIR/uber.frag.spv" | sed 's/unsigned char.*\[\] = {//;s/};$//' | \
    python3 -c "
import sys
data = bytes([int(x.strip().rstrip(','), 16) for x in sys.stdin.read().replace('\n',' ').split(',') if x.strip()])
words = []
for i in range(0, len(data), 4):
    w = int.from_bytes(data[i:i+4], 'little')
    words.append(f'0x{w:08x}')
for i in range(0, len(words), 8):
    print('    ' + ', '.join(words[i:i+8]) + ',')
" >> "$OUTDIR/vulkan_shaders_spirv.h"
echo "};" >> "$OUTDIR/vulkan_shaders_spirv.h"

VERT_SIZE=$(wc -c < "$TMPDIR/uber.vert.spv")
FRAG_SIZE=$(wc -c < "$TMPDIR/uber.frag.spv")
echo "[Shaders] Done! Vertex: ${VERT_SIZE} bytes, Fragment: ${FRAG_SIZE} bytes"
echo "[Shaders] Output: $OUTDIR/vulkan_shaders_spirv.h"
